#!/usr/bin/env bash

chmod -R 775 /var/www/api/storage /var/www/api/boostrap/cache

if [ ! -z "$WWWUSER" ]; then
    usermod -u $WWWUSER api
	chown -R $WWWUSER:www-data /var/www/api/storage /var/www/api/boostrap/cache
	echo "chown $WWWUSER:www-data /var/www/api/storage /var/www/api/boostrap/cache"
else
	chown -R www-data:www-data /var/www/api/storage /var/www/api/boostrap/cache
	echo "chown www-data:www-data /var/www/api/storage /var/www/api/boostrap/cache"
fi

